# Generated by Django 6.0.6 on 2026-06-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home', 'Home & Kitchen'), ('beauty', 'Beauty'), ('sports', 'Sports & Fitness')], max_length=32)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=4.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='PriceRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_demand', models.FloatField()),
                ('expected_revenue', models.FloatField()),
                ('expected_profit', models.FloatField()),
                ('purchase_likelihood', models.FloatField()),
                ('strategy', models.CharField(default='maximize_revenue', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='pricing.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('competitor_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_of_week', models.IntegerField()),
                ('is_weekend', models.BooleanField(default=False)),
                ('is_holiday_season', models.BooleanField(default=False)),
                ('site_traffic', models.IntegerField(default=0)),
                ('units_sold', models.IntegerField(default=0)),
                ('converted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='pricing.product')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['product', 'date'], name='pricing_sal_product_131293_idx')],
            },
        ),
    ]
